apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimysqlservice
  template:
    metadata:
      labels:
        app: mimysqlservice
    spec:
      containers:
        - name: mimysqlservice
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secreto
                key: rootpassword 
          - name: MYSQL_DATABASE
            value: "universidadX"
          - name: MYSQL_USER
            value: "cliente"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secreto
                key: userpassword
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mivolumenparamysql
      volumes:
        - name: mivolumenparamysql
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: mimysqlservice
  ports:
    - name: mimysqlservice
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: mimysqlservice
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306